### PR TITLE
Allow to filter functions based on its namespace

### PR DESCRIPTION
**Pull request by flusflas**
## Description
This pull request adds a `Namespace` field in the `ControllerConfig` struct to enable function filtering by namespace. This way, if a namespace is provided, only functions from that namespace will handled (mapped and, consequently, invoked).

I know contributing guidelines ask to raise a proposal before opening a pull request, but this is a needed feature for me, so I'm sorry for the rush.

## Motivation and Context
In a multi-tenant environment, where there are many namespaces which are supposed to be isolated, the connector is not very useful because it ignores the namespaces the functions are in.

## How Has This Been Tested?
A new test function with two sub-tests has been added to `function_list_builder_test.go` to cover filtering and non-filtering (default) use cases.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi thanks for your interest in the project.

You will need to raise an issue for discussion before we can consider reviewing a PR or solution.

In the issue make sure you detail your openfaas usage and whether this is a real problem you've faced, and how many namespaces you have, or whether it's a hypothesis / nice to have.

Please read ["I want to contribute on GitHub" carefully.](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#i-want-to-contribute-on-github)
 
Alex

**Review by alexellis — CHANGES_REQUESTED** [review]
This needs to be proposed in an issue with as much context as possible

**Comment by mathieuforest** [comment]
@flusflas any interest to complete this PR?

**Comment by flusflas** [comment]
Some conflicts have appeared since the time I made this PR. I just updated the branch.

**Pull request closed without merging**
