### PR TITLE
Extract interface from 'types.Controller'.

### PR DESCRIPTION
**Pull request by bmcstdio**
This PR extracts an interface from `types.Controller` in order to make it test-friendly for consumers of the SDK.

### CODE REVIEW

**Comment by alexellis** [comment]
This had conflicts, so I've merged and conflicts fixed, thank you @bmcstdio

**Comment by bmcstdio** [comment]
@alexellis thank you, but I don't think the conflicts were properly fixed:

https://github.com/openfaas-incubator/connector-sdk/blame/master/types/controller.go#L139

I am afraid `0.5.0` is unusable as it is.

**Comment by alexellis** [comment]
Feel free to send a follow-up pull request.

**Comment by bmcstdio** [comment]
@alexellis done. It was not the only issue, it seems.

**Pull request merged**
